# Generated by Django 5.2.1 on 2025-05-18 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postupload',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postupload',
            name='unlike',
            field=models.ManyToManyField(blank=True, related_name='unlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
